<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6bw71DM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6bw71DM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6bw71DM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6bw71DM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6bw71DM\App_KernelDevDebugContainer([
    'container.build_hash' => '6bw71DM',
    'container.build_id' => 'a31e8cd3',
    'container.build_time' => 1648478733,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6bw71DM');
